name: 'Kubernetes Download Volume'
description: 'This action makes it easy to download any folder on a Persistent Volume (Claim) to the local filesystem.'
branding:
  icon: 'arrow-down'
  color: 'blue'
inputs:
  kubeConfig:
    description: 'Base64 encoded kubeconfig, either this or the KUBECONFIG environment variable is required'
    required: true
    default: ''
  name:
    require: true
    default: ''
    description: 'Name of the Kubernetes Persistent Volume Claim'
  size:
    required: true
    default: '5Gi'
    description: 'Amount of disc space to assign the Kubernetes Persistent Volume (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kubeConfig }}
    - ${{ inputs.name }}
    - ${{ inputs.size }}
