name: 'Kubernetes Download Volume'
description: 'This action makes it easy to download any folder on a Persistent Volume (Claim) to the local filesystem.'
branding:
  icon: 'arrow-down'
  color: 'blue'
inputs:
  kubeConfig:
    description: 'Base64 encoded kubeconfig, either this or the KUBECONFIG environment variable is required'
    required: true
    default: ''
  volume:  # id of input
    description: 'Kubernetes PV to mount'
    required: true
    default: ''
  sourcePath:  # id of input
    description: 'Folder to download from the PV'
    required: false
    default: ''
  outputPath:  # id of input
    description: 'Folder to download the PV into'
    required: false
    default: 'k8s-volume-download'
  timeout:
    description: 'number of seconds to wait when a pod is unschedulable'
    required: false
    default: '260'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kubeConfig }}
    - ${{ inputs.volume }}
    - ${{ inputs.sourcePath }}
    - ${{ inputs.outputPath }}
    - ${{ inputs.timeout }}
